////////////////////////////////////////////////////////////////////////////
// Problem 1 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.

function solve1() {
  var sum = 0;
  for (var i = 999; i >= 0; i--) {
    if (i % 5 == 0 || i % 3 == 0) {
      sum += i;
    }
  }
  return sum;  
}

////////////////////////////////////////////////////////////////////////////
// Problem 2 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function solve2() {
  var fib = [1, 2];
  var sum = 2;

  function getNext()  {
    next = fib[0] + fib[1];
    fib.shift();
    fib.push(next);
  }

  getNext();

  while (next < 4000000) {
    if (next % 2 == 0) {
      sum += next;
    }
    getNext();
  }
  return sum;
}

////////////////////////////////////////////////////////////////////////////
// Problem 3 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// The prime factors of 13195 are 5, 7, 13 and 29.
// What is the largest prime factor of the number 600851475143 ?

function solve3() {
  var num = 600851475143;
  var res = 0;
  var guess = 0;
  for (var i = 2; i <= (num/2); i++) {
    guess = Math.floor(num / i);
    if (isFactor(num, guess) && isPrime(guess)) {
      return guess;
    }
  };  
}

function isFactor(big, small) {
  return big % small === 0;
}

function isPrime(n) {
  var sqrt = Math.sqrt(n);
  for (var i = 2; i <= sqrt; i++) {
    if (n % i === 0) {
      return false;
    }
  }
  return true;
}

////////////////////////////////////////////////////////////////////////////
// Problem 4 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
// Find the largest palindrome made from the product of two 3-digit numbers.

function solve4() {   
  var max = 999*999;
  var min = 100*100;
  var prod = 0;
  var res = 0;
  for (var i1 = 999; i1 >= 100; i1--) {
    for (var i2 = i1; i2 >= 100; i2--) {
      prod = String(i1 * i2);
      var palind = true;
      for (var i = 0; i < Math.floor(prod.length/1); i++) {
        if (prod.charAt(i) != prod.charAt(prod.length - 1 - i)) {
          palind = false;
        }
      }
      if (palind && Number(prod) > res) {
        res = Number(prod);
      }
    }
  }
  return res;
}

////////////////////////////////////////////////////////////////////////////
// Problem 5 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
// What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

// x <= ceil/2 is out since it will be represented in (ceil/2..ceil]
// ie any multiple of ceil is a multiple of ceil/2

function solve5() {   
  var ceil = 20;
  var floor = ceil/2;
  var factors = {};
  for (var i = ceil; i > floor; i--) {
    addFactorCount(factors, getPrimeFactors(i));
  };
  var res = 1;
  for (factor in factors) {
    res = res * (Math.pow(factor, factors[factor]));
  }
  return res;
}

// example factor_arr: [2, 2, 3]
function addFactorCount(old_factors, factor_arr) {
  var new_factors = {};
  for (var i = factor_arr.length - 1; i >= 0; i--) {
    if (new_factors[factor_arr[i]]) {
      new_factors[factor_arr[i]]++;
    } else {
      new_factors[factor_arr[i]] = 1;
    }
  }
  for (factor in new_factors) {
    if (old_factors[factor]) {
      old_factors[factor] = Math.max(old_factors[factor], new_factors[factor]);
    } else {
      old_factors[factor] = new_factors[factor];
    }
  }
}

function getPrimeFactors(n) {
  if (isPrime(n)) {
    return [n];
  } else {
    var factor_arr = [];
    for (var i = Math.floor(n/2); i >= 2; i--) {
      if (isFactor(n, i) && isPrime(i)) {
        factor_arr.push(i);
      }
    }
    var prod = factor_arr.reduce(function(a,b){ return a*b; }) ;
    if (prod == n) {
      return factor_arr;
    } else {
      factor_arr.push(getPrimeFactors(n / prod));
      return flatten(factor_arr);
    }
  }
}

function flatten(arr) {
  return arr.reduce(function (flat, toFlatten)  {
    return flat.concat(Array.isArray(toFlatten) ? flatten(toFlatten) : toFlatten);
  }, []);
}

////////////////////////////////////////////////////////////////////////////
// Problem 6 ///////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

// The sum of the squares of the first ten natural numbers is,
// 12 + 22 + ... + 102 = 385
// The square of the sum of the first ten natural numbers is,
// (1 + 2 + ... + 10)2 = 552 = 3025
// Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
// Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

function solve6() {   
  var n = 100;
  var sum_of_squares = 0;
  var square_of_sum  = Math.pow(n * (n + 1) / 2, 2);
  for (var i = n; i > 0; i--) {
    sum_of_squares += Math.pow(i, 2);
  };
  return Math.abs(square_of_sum - sum_of_squares);
}